# Generated by Django 5.2.7 on 2025-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('hamster', 'Hamster'), ('love-birds', 'Love Birds')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('pet_holder', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(choices=[('Sandwich', 'Sandwich'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Pizza', 'Pizza'), ('Other', 'Other')], max_length=20)),
                ('snack_type', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=6)),
                ('snack_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pizza_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sandwich_name', models.CharField(blank=True, max_length=100, null=True)),
                ('beverage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
