# Generated by Django 5.2.7 on 2026-09-25 08:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_replace_old_menu_form"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coffee", "Coffee"),
                            ("beverages", "Beverages"),
                            ("snacks", "Snacks"),
                            ("sandwiches", "Sandwiches"),
                            ("pizza", "Pizza"),
                            ("desserts", "Desserts"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_veg", models.BooleanField(default=True)),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Image URL or path, e.g. /images/donut.webp",
                        max_length=300,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Untick when sold out."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on the home page."
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="pet_holder",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="pet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dog", "Dog"),
                    ("cat", "Cat"),
                    ("hamster", "Hamster"),
                    ("love-birds", "Love Birds"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Received"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("dine_in", "Dine in"), ("takeaway", "Takeaway")],
                        default="dine_in",
                        max_length=10,
                    ),
                ),
                ("table_number", models.CharField(blank=True, max_length=10)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cafe.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cafe.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="Start hour, 24h clock (e.g. 15 = 3 PM)."
                    ),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "pet_preference",
                    models.CharField(
                        choices=[
                            ("any", "Any pet"),
                            ("dog", "Dogs"),
                            ("cat", "Cats"),
                            ("hamster", "Hamsters"),
                            ("love-birds", "Love birds"),
                        ],
                        default="any",
                        max_length=12,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Visited"),
                            ("no_show", "No-show"),
                        ],
                        default="confirmed",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "slot"],
                "indexes": [
                    models.Index(
                        fields=["date", "slot", "status"],
                        name="cafe_bookin_date_a5adba_idx",
                    )
                ],
            },
        ),
    ]
